### ISSUE TITLE
Is there a way to disable built-in indexes?

### ISSUE THREAD

**Issue by mcfarljw** [GoogleCloudPlatform/gcloud-node#1033]
If I recall correctly when using python it's possible to specify which properties use the built-in index. Is this something that is or will be possible with the node interface when saving?

**Comment by stephenplusplus** [comment]
@pcostell

**Comment by pcostell** [comment]
No this is not possible (yet!). This isn't possible in python either. In python if you specify `indexed=False` this disables the property in *all* the indexes, not just the built in indexes.

You can get the same results using the `excludeFromIndexes` property. Just remember that this also prevents any composite index entries that use that property from being saved for that entity.

**Comment by mcfarljw** [comment]
Ah right, I guess what I really meant was the ability to disable the built-in indexing on certain properties across all the entities in a kind. But based on your response this sounds like it is planned.

**Comment by pcostell** [comment]
Yes, it is not possible but we are hoping to provide this functionality in the future.

To clarify -- this isn't possible in Datastore on GAE either. If you specify `indexed=False` in your model definition it just applies this to all entities created from that point onward. It doesn't retroactively change indexing information.

Since this is a Datastore feature request (and not specific to gcloud-node), I've opened a new issue here: https://github.com/GoogleCloudPlatform/google-cloud-datastore/issues/83.
