### ISSUE TITLE
gcloud-node and Openshift

### ISSUE THREAD

**Issue by FredMichel** [GoogleCloudPlatform/gcloud-node#1051]
Hello Team,

I am using the component gcloud-node to access (read/write) Google storage bucket from my node-js application. It works fine when server starts locally (localhost), I am able to upload files within the remote bucket using the below function:
```js
 function writeLocalFileToRemoteStorage(localName, remoteName, callback) {
    var localReadStream = fs.createReadStream(localName);
    var remoteWriteStream = bucket.file(remoteName).createWriteStream();
    localReadStream.pipe(remoteWriteStream);
    callback(null, 'OK');
  }
```

However, after pushing the code to my Openshift instance, an exception is raised :
```
/var/lib/openshift/11abcdefe0000000c8/app-root/runtime/repo/node_modules/mkdirp/index.js:90
                    throw err0;
                          ^
Error: EACCES, permission denied '/var/lib/openshift/11abcdefe0000000c8/.config'
```
It seems that the component  needs .config folder and it tries to create it. Unfortunately, Openshift denied to write the folder where .config is supposed to be.
How can I fix that issue?
Thank you in advance for your support to help me fix that issue. 

PS : I am using json keyfilename for authentication.

**Comment by stephenplusplus** [comment]
Just to first explain the pieces that are involved here:

We (gcloud-node) use a library called [`gcs-resumable-upload`](http://gitnpm.com/gcs-resumable-upload), which uses a library called [`configstore`](http://gitnpm.com/configstore). That's the library that's failing to create the config file due to the permissions error.

Performing a resumable upload requires persisting small bits of data, which is why configstore is used. So, a quick fix would be simply disabling resumable uploads:

```diff
- var remoteWriteStream = bucket.file(remoteName).createWriteStream();
+ var remoteWriteStream = bucket.file(remoteName).createWriteStream({ resumable: false });
```

However, if that's not ideal, you will have to find a way to give the user running your Node app permissions to the `.config` directory. I don't have any experience with Openshift to know if there are any tricks to solve this.

[This issue](https://github.com/yeoman/yo/issues/348) might be a dead-end since it's not related to Openshift, but maybe check it out in case it helps in some way.

Please report back if you find a solution!

**Comment by FredMichel** [comment]
Thank for that answer. Root cause is clear. I already tried the workaround you have suggested (resumable to false) but the same exception is raised.

Openshift allows to write only in specific folders called data. Is it possible to force the component to write .config in that specific folder? For instance if I provide the full path to that folder as a parameter?

Thanks a lot

**Comment by stephenplusplus** [comment]
@sindresorhus -- is there a way to handle custom paths with Configstore, or anything else you can think of for this situation?

**Comment by stephenplusplus** [comment]
@FredMichel it's a bug if `gcs-resumable-upload` is being used when you didn't want a resumable upload: https://github.com/GoogleCloudPlatform/gcloud-node/blob/8dbf0fd35a924f34a777942273affc79a954fc26/lib/storage/file.js#L791-L795. Can you double check that happens when you providing `resumable: false` and also let me know the version of gcloud you're running?

**Comment by sindresorhus** [comment]
`configstore` abides [XDG](http://standards.freedesktop.org/basedir-spec/basedir-spec-0.6.html), so you could set the environment variable `XDG_CONFIG_HOME` to a writeable location.

**Comment by FredMichel** [comment]
@stephenplusplus @sindresorhus : Guys thank you so much for your prompt answers !

A. Solution  `resumable :false ` works !
In fact, my mistake was 
```javascript
var remoteWriteStream = bucket.file(remoteName).createWriteStream({ options : {resumable: false }});
```
instead of 
```javascript
var remoteWriteStream = bucket.file(remoteName).createWriteStream({ resumable: false });
```
Documentation confuses me : https://googlecloudplatform.github.io/gcloud-node/#/docs/v0.27.0/storage/file?method=createWriteStream


B. Environment variable `XDG_CONFIG_HOME` does not work.
I have set up this environment variable to the right writable path but the same exception is raised.
This is the the environment variable : `XDG_CONFIG_HOME=/var/lib/openshift/11abcdefe0000000c8/app-root/data`

Thank you guys !

**Comment by stephenplusplus** [comment]
Woo, glad it's resolved!

**Comment by musemind** [comment]
Same problem on DigitalOcean.
`createWriteStream({ resumable: false })` solved it! Thanks!
