### ISSUE TITLE
networkInterfaces resource upon createVM completion

### ISSUE THREAD

**Issue by brinck** [GoogleCloudPlatform/gcloud-node#1085]
The createVM api exposes four variables on call back, along with a callback variable. As far as I could see, the networkInterfaces resource for that given VM is not accessible anywhere. In other words, it is not possible to get the external IP for the VM should one have been assigned, a part from getting all VMs after the creation of a particular one. 

```
zone.createVM(name, config, function(err, vm, operation, apiResponse){
    operation.on('complete', function(metadata){
        // metadata, vm, operation, apiResponse don't include the networkInterfaces
    });
})
```
Am I missing something, or is this feature not yet implemented? And if not, I like to request it as an enhancement. Thanks!

**Comment by stephenplusplus** [comment]
I think the issue is the `metadata` in the context of `operation.onComplete` is the operation's properties. What you need to do is make another call on `vm` to refresh the metadata:

```js
zone.createVM(name, config, function(err, vm, operation, apiResponse){
    operation.on('complete', function(){
      vm.getMetadata(function(err, metadata){
        // metadata.networkInterfaces[0].accessConfigs[0].natIP
      });
    });
})
```

Here's an example of doing that in gcloud-deploy: https://github.com/stephenplusplus/gcloud-deploy/blob/25233819ece801bc556957153e64d78a09993615/index.js#L221

Let me know if you run into any issues!

**Comment by brinck** [comment]
Thanks for the quick and swift feedback. It worked!
