### ISSUE TITLE
Error: read ECONNRESET

### ISSUE THREAD

**Issue by maasencioh** [GoogleCloudPlatform/gcloud-node#1122]
Hello, maybe I'm doing a silly question, but I'm working in [this project](https://github.com/maasencioh/solmaforo/tree/develop) and I have an error when I load a file

```
solmaforo/controllers/upload.js:29
                        if (err) throw err;
                                 ^

Error: read ECONNRESET
    at exports._errnoException (util.js:837:11)
    at TLSWrap.onread (net.js:544:26)
```

It's suppose to be a socket error, but I'm not able to track it down, do you have any clue?

PS: [This](https://gist.github.com/maasencioh/8b908aa8f31186f67b6b) is an example of a file to load

Thanks!

**Comment by stephenplusplus** [comment]
I'm trying to reproduce, but hit a roadblock. The regex [here]( https://github.com/maasencioh/solmaforo/blob/674f8ea3ab024737419d02e44d870136c22cbf90/controllers/upload.js#L22) isn't finding any matches from the file from the gist.

I did notice the callback to the `models.store.get` function is being immediately invoked: https://github.com/maasencioh/solmaforo/blob/674f8ea3ab024737419d02e44d870136c22cbf90/controllers/upload.js#L29 -- is that intentional, or maybe I'm misreading?

**Comment by stephenplusplus** [comment]
*Oh, and you should probably not check in your key file JSON :)*

**Comment by stephenplusplus** [comment]
Hey @maasencioh, I'm going to close the issue, but please re-open if you can reproduce or help me get the demo up and running. As of now, it seems like maybe a local issue, but I'm still happy to take a look if it's anything I can fix.
