### ISSUE TITLE
Is the optional dependency really worth it?

### ISSUE THREAD

**Issue by jgeewax** [GoogleCloudPlatform/gcloud-node#1299]
Re https://github.com/pkgcloud/pkgcloud/issues/452

The issue is that optional deps show a scary warning message, often confusing our users (hell, even I've been confused at first until I read the error message and see "warning").

The CRC32 stuff is performance optimization only, right? If so, what's stopping us from wrapping the require statement in a try/catch ? And defaulting to the required dependency?

Then when people go "this is too slow! make it faster!" we say "no problem, just run `npm install <whatever>`" ? Sounds like something to put in the FAQ or a "performance" section of the docs when people go looking for that?

**Comment by stephenplusplus** [comment]
If we don't care to default to the benefits of hardware crc32c, then let's just drop it altogether. If we do get users reporting it being too slow, we can rethink our options?

**Comment by jgeewax** [comment]
I'd like it if the answer to someone caring was "type `npm install ...`" rather than "oh well we used to....". Make sense?

Can we do the conditional import, but just not list it as a requirement?

**Comment by stephenplusplus** [comment]
Yeah, we can do it. It's just not a pattern I've seen before. Our code gets a little more complicated and we won't have any metrics around if anyone is actually noticing the software hashing (installing the `crc32c` module themselves). That's why I would rather wait to hear anyone complain before we go to those lengths. The time to implement after any complaints would be very minimal. Users can also revert to an older version of our library until that release in the meantime.

**Comment by stephenplusplus** [comment]
Let's scoot with the try/catch. Firebase needs the crc32c, so hanging them out to dry would be sad.
