### ISSUE TITLE
Require gcloud throws error

### ISSUE THREAD

**Issue by valentinvichnal** [GoogleCloudPlatform/gcloud-node#1394]
Hey, when I use gcloud in plain nodejs app it works fine, but with Meteor.js I can't make it to work.

The plain node app installs and runs gcloud and the grpc deps without any error:
```
node -v: 4.4.5
npm -v: 3.9.6
```
```bash
grpc@0.14.1 install D:\projects\demo-app-node\node_modules\grpc
node-pre-gyp install --fallback-to-build

[grpc] Success: "D:\projects\demo-app node\node_modules\grpc\src\node\
extension_binary\grpc_node.node" is installed via remote
```

The Meteor.js app can install gcloud too but it gives the following warnings:
```bash
  "fast-crc32c" in
/D/projects/demo-app-meteor/node_modules/hash-stream-validation/index.js
(os.windows.x86_32)
  "memcpy" in
/D/projects/demo-app-meteor/node_modules/bytebuffer/dist/ByteBufferNB.js
(os.windows.x86_32)

If you notice problems related to these missing modules, consider running:

meteor npm install --save fast-crc32c memcpy
```
I can install fast-crc32c, but memcpy gives a lot of error on Windows 8 and can't install it.
Since bytebuffer is only a devDependency this shouldn't be a problem.
```
Meteor used old 0.10.45 node version,
the latest meteor release use the same node and npm version as the plain app:
node -v: 4.4.5
npm -v: 3.9.6
```

When I require gcloud:
`var gcloud = require('gcloud');`

Meteor throws this error:
```javascript
C:\Users\user\AppData\Local\.meteor\packages\meteor-tool\1.4.0-beta.1\mt-os.windows.x86_32\dev_bundle\server-lib\node_modules\fibers\future.js:280
throw(ex);
Error: %1 is not a valid Win32 application
\\?\D:\projects\demo-app-meteor\node_modules\grpc\src\node\extension_binary\grpc_node.node
at Error (native)
at Object.Module._extensions..node (module.js:434:18)
at Module.load (module.js:343:32)
at Module.Mp.load (C:\Users\user\AppData\Local\.meteor\packages\babel-compiler\6.8.4-beta.1\npm\node_modules\reify\node\runtime.js:16:23)
at Function.Module._load (module.js:300:12)
at Module.require (module.js:353:17)
at require (internal/module.js:12:17)
at Object.<anonymous> (D:\projects\demo-app-meteor\node_modules\grpc\src\node\src\grpc_extension.js:38:15)
at Module._compile (module.js:409:26)
at Object.Module._extensions..js (module.js:416:10)
```

Any help would be appreciated.

**Comment by stephenplusplus** [comment]
Maybe something in this issue will help? http://stackoverflow.com/questions/37742610/meteor-cant-run-gcloud-on-server-side

bytebuffer is a dependency of protobufjs which is a dependency of grpc, so it's not a dev dependency. Which version of gcloud are you using?

Also, your logs say Meteor is using Node version 0.10.45. Is there a way to use a newer version? We only officially support 0.12 and newer.

Sorry that I don't know Meteor better. Your best bet might be chiming into the StackOverflow post. Since this isn't a bug with this project, I'm going to close the issue, but we can continue discussing if SO cannot help.

**Comment by valentinvichnal** [comment]
Thanks for the link, I use the 0.36.0 gcloud version.
This meteor version now uses 4.4.5 and not 0.10.45, it wasn't in the log, I just put this line into a wrong block, sorry.
I looked into the bytebuffer source code and memcpy is optional, it only makes copy faster but the code should work without it.

Any advice how should I use Google Datastore without your module?

**Comment by micahalcorn** [comment]
I am having a similar problem on Ubuntu (Node 4.4.7) when I try to deploy my Meteor app, which works fine on my local OS X environment. [Here is my stack trace](http://pastie.org/private/wapafgb52x08gbjzeisnrg) showing problems with `grpc` and `node-pre-gyp`, both which I have manually installed. Interestingly, the SO question that @stephenplusplus linked has a comment pointing to an old Meteor Package that I created for wrapping `gcloud-node`, which is no longer appropriate since Meteor handles direct importing of NPM packages and is running LTS Node.

See also https://github.com/meteor/meteor/issues/7301, thanks. 🙏
