### ISSUE TITLE
gRPC emulator fails to run

### ISSUE THREAD

**Issue by rommguy** [GoogleCloudPlatform/gcloud-node#1477]
#### Environment details

  - OS: Mac OS X, x86_64
  - Node.js version:  6.2.1
  - npm version: 3.9.3
  - gcloud-node version: 
```
Google Cloud SDK 121.0.0
beta 2016.01.12
bq 2.0.24
bq-nix 2.0.24
cloud-datastore-emulator 1.1.1
core 2016.08.05
core-nix 2016.06.24
gcd-emulator v1beta3-1.0.0
gcloud
gsutil 4.20
gsutil-nix 4.19
```

#### Steps to reproduce

  1. run  gcloud beta emulators datastore start --no-legacy
  2. error printed - Invalid project directory: /Users/guyr/.config/gcloud/emulators/datastore. Did you create it using 'create'?

When I specify my own directory with --data-dir, I get the same error.

Thanks!

**Comment by stephenplusplus** [comment]
@pcostell any ideas? This is what I was getting a while back: https://github.com/GoogleCloudPlatform/gcloud-node/issues/1331#issuecomment-223384865 -- but when I run the steps from this issue, everything works properly for me.

**Comment by rommguy** [comment]
@stephenplusplus I've read the issue you linked, but it says to run 'gcd create', and there is no 'create' command with gcloud-node tool

**Comment by pcostell** [comment]
The gcloud tool implements `start` as `gcd create` followed by `gcd start`. After the directory is first created, `gcd create` is no longer called.

It looks like there may be issues if you use both the old emulator (v1beta2/v1beta3 proto-over-HTTP only) and the new one (specified with the `--no-legacy` flag, which supports v1beta3 gRPC, JSON, and proto-over-HTTP). 

In particular, if the first time you make the call you run with `--no-legacy`, then try running the legacy version, it will fail because the legacy version has extra information it needs in the data directory.

I would recommend clearing out your data directory and trying again. On linux/mac systems, I believe this lives by default in `~/.config/gcloud/emulators/datastore`. Try backing up the folder then deleting it and running the `gcloud beta datastore emulator start` command again.

**Comment by rommguy** [comment]
Thank you very much!
I used a new and empty directory with --data-dir option, and it simply worked.
Too bad the error message wasn't informative, would have saved a lot of time.

I have a different problem now, where the env-init command sets ports different than the ones the emulator uses, but I will open a separate issue for that

Thanks again!
