### ISSUE TITLE
general: Investigate using square/protob

### ISSUE THREAD

**Issue by jgeewax** [GoogleCloudPlatform/gcloud-node#249]
https://github.com/square/protob looks like it might be something worth investigating... Just figured I'd mention that here so we don't lose track of it.

**Comment by ryanseys** [comment]
I don't think this `protob` has really taken off as a library and doesn't seem to be a very active or open project (no ci integration, no issues opened or closed, no PRs). I think the performance we get from Protobuf.js is good (and `protob` uses code from the library anyway). I don't think we will need to port our code to another protobuf library anytime soon and if we REALLY need to in the future, I have faith we will find the right solution in due time, so I'm closing this issue. Feel free to open if you think we might benefit from a better protobuf library or otherwise think we should continue to investigate it further.
