### ISSUE TITLE
Make it easy to open a documentation bug (or fork docs) from the docs themselves

### ISSUE THREAD

**Issue by jgeewax** [GoogleCloudPlatform/gcloud-node#348]
Related to https://github.com/GoogleCloudPlatform/gcloud-python/issues/98

Can we add a button near "See version history" that is something like "Edit on GitHub" or "See something wrong? Report an issue!" or something like that?

It'd be nice to make it easy for external developers to give feedback (or improve) our documentation.

**Comment by stephenplusplus** [comment]
I like the "Report an Issue" option since our docs are inlined in the source code. I think it would be unexpected to have a user click "Edit the docs" and be taken to a .js file.

We have the "Edit on GitHub" on the MD-generated pages: https://googlecloudplatform.github.io/gcloud-node/#/faq and https://googlecloudplatform.github.io/gcloud-node/#/troubleshooting. I'll follow the same convention regarding placement & style for the new button on the API doc pages.

**Comment by jgeewax** [comment]
SGTM :+1:

**Comment by stephenplusplus** [comment]
PR sent: #356
