### ISSUE TITLE
Set initial metadata file on first upload

### ISSUE THREAD

**Issue by temka1234** [GoogleCloudPlatform/gcloud-node#363]
In my project i want to create an empty file in google storage with ```metadata``` in one step. 
I found this note in ```gcloud-node/lib/storage/file.js```:
```
...
 * @param {object=} metadata - Metadata to set on the object. This is useful
 *     when you are creating a file for the first time, to prevent making an
 *     extra call to `setMetadata`.
...
function File(bucket, name, metadata) { }
```
But i cant find any code that use ```file.metadata``` parameter in ```createWriteStream``` or ```getWritableStream_```.
Also ```storage.bucket.file(name)``` method that created new instance of ```File``` not contains ```metadata``` parameter.

I know, that i can use ```createWriteStream(metadata)```. This is the only way?

**Comment by stephenplusplus** [comment]
The File constructor taking a metadata argument is a relic of old code, I believe.

The problem is, creating a File instance (ex: through `storage.bucket.file()`) shouldn't have any async/api effects. So, it would be confusing if you said...

```js
var file = myBucket.file('file-name', { metaprop: 'value' })
file.getMetadata(function(err, metadata) { /* no metaprop here */ })
```

...because the metadata you "set" wasn't actually set. 

Instead, you can explicitly set metadata on a file:
```js
var file = myBucket.file('file-name')
file.setMetadata({ metaprop: 'value' }, function(err, metadata) {})
```

Or use `bucket.upload`: http://googlecloudplatform.github.io/gcloud-node/#/docs/v0.12.0/storage/bucket?method=upload

**Comment by temka1234** [comment]
Thanks for the reply!
