### ISSUE TITLE
Lack of developer documentation

### ISSUE THREAD

**Issue by ludoch** [GoogleCloudPlatform/gcloud-node#479]
See https://googlecloudplatform.github.io/gcloud-node/#/docs/v0.13.1/datastore
It mentions "some convenience methods"  

Convenience based on What?
Do I need to master the low level Datastore APIs? Imo, the gcloud layer should be self sufficient and complete for documentation, exposing all the Datastore concepts assuming the user knows nothing, and without the need for the user to read other docs....

The doc issue seems generic for all gcloud APIs for all the runtimes (same for Java, I did not look at ruby)

**Comment by ryanseys** [comment]
Hi @ludoch thanks for the feedback. We pride ourselves on our documentation so it's sad to hear you're not satisfied. 

Datastore is a rather tricky API to make an idiomatic client for while also giving users like you the ability to do everything you need to do. This is because the Datastore concepts are strongly linked to the API itself, e.g. what a key is, what an entity is, how these play in when you're just trying to save your data to the datastore. We hope this library tries to soften the edges by abstracting away the details that don't matter and in some cases making assumptions on what you want to do given the specific context.

In any case, we believe that as a developer you should ramp yourself up on the various high level concepts of each API from https://cloud.google.com/docs/. We should also likely make this clear in our docs.

> "some convenience methods"

This is just talking about the `datastore#double` and `datastore#int` methods available on that object for specifying the type of number you'd like to save to the datastore because JavaScript only has a single number type.

We'd suggest you start looking at the `dataset` documentation because that gives you the power to make calls with the API. We should also make this more clear in our documentation.

> The doc issue seems generic for all gcloud APIs for all the runtimes

If you believe that other languages documentation is also bad, I'd suggest you open separate issues on their libraries for your concerns as different people work on different libraries.

**Comment by stephenplusplus** [comment]
It would be nice to add in a quick link in each module's "overview" section to the official docs.

**Comment by stephenplusplus** [comment]
Sent in #507 that links to Google developer docs for each service. This will hopefully give newcomers an easy path to all the information they will need.
