### ISSUE TITLE
Support Google analytics API

### ISSUE THREAD

**Issue by leibale** [GoogleCloudPlatform/gcloud-node#493]
[Api overview](https://developers.google.com/analytics/devguides/config/mgmt/v3/).
thanks :)

**Comment by ryanseys** [comment]
Hi @leibale thanks for the suggestion. This API is beyond the scope of this client library, as `gcloud-node` deals strictly with cloud architecture APIs such as Storage, Datastore, PubSub and BigQuery. More support for other APIs are on the way such as Cloud DNS.

I would recommend taking a look at https://github.com/google/google-api-nodejs-client which should give you access to this API through an officially Google-supported node client.

**Comment by leibale** [comment]
http://i.imgur.com/Cqp1j8Q.png

**Comment by ryanseys** [comment]
Hi @leibale sorry for the misunderstanding, but you're looking at the full list of Google APIs available. This library doesn't deal with every API that Google offers. The scope of this client library is related to the products found at https://cloud.google.com/ 

![image](https://cloud.githubusercontent.com/assets/163873/7167333/2cc27b12-e382-11e4-811b-24ccc03f6a68.png)

Hope this clears things up.

Using the `googleapis` npm package (found at [`google/google-api-nodejs-client`](https://github.com/google/google-api-nodejs-client/)) should suit your needs for the Google Analytics API. You can get started in as easy as:

``` js
var google = require('googleapis');
var auth = google.auth.JWT(/* ... */); // authenticate here
var analytics = google.analytics('v3');
analytics.data.ga.get({ /* parameters here */, auth: auth }, function(err, body) {
  // Use the response here
});
```

See the repo docs in order to learn more about using that API client.

**Comment by leibale** [comment]
ok, i check this later.
