### ISSUE TITLE
pagination sets next query even though there are no more results

### ISSUE THREAD

**Issue by rakyll** [GoogleCloudPlatform/gcloud-node#5]
If the query contains a limit, backend keeps returning MORE_RESULTS_AFTER_LIMIT even though there are none.

~~~~ js
var q = ds.query(['Kind']).limit(10);
~~~~

We make an end cursor comparison to detect where to terminate pagination, but it costs us one extra query that returns an empty list of results.

**Comment by stephenplusplus** [comment]
Our default pagination behavior has changed dramatically since this issue (almost exactly 1 year ago!). By default, we now run query after query until no results are returned. This behavior can be switched off to revert to manual pagination. But, this specific issue no longer applies to our library, and whatever is going on in "b/10688926", that's where the misleading backend behavior issue can be tracked.
