### ISSUE TITLE
Why did we go with the Protobuf API for Datastore rather than the REST/JSON API?

### ISSUE THREAD

**Issue by jgeewax** [GoogleCloudPlatform/gcloud-node#517]
Just curious -- was there an issue with the REST/JSON API ?

**Comment by stephenplusplus** [comment]
Not sure, @silvolu and @rakyll were behind that. Not very informative, but for reference, #112 is the PR where we switched.

**Comment by ryanseys** [comment]
The reason is because JSON/REST has a much higher size overhead compared to Protobuf at the network layer and possibly other layers. Datastore is meant to be very fast and size efficient with potentially high throughout, so requests should be as small as possible. This allows a higher throughput of requests compared to using JSON. We use JSON for the other API requests because their payloads are potentially much larger, making the difference between a protobuf request and a JSON one negligible.

**Comment by jgeewax** [comment]
Cool - thanks :)
