### ISSUE TITLE
Make the homepage example have two tabs (one for "anywhere" another for "GCE")

### ISSUE THREAD

**Issue by jgeewax** [GoogleCloudPlatform/gcloud-node#538]
Would be really cool if we could toggle between the "Anywhere" state (where you need to specify authentication stuff) and the "inside GCE" state (where auth happens automagically.

**Comment by ryanseys** [comment]
We accept PRs! ^_^

This is a neat idea but there's really nothing different except the one
small example that happens at the beginning where the key doesn't need to
be specified. I feel this would actually confuse users because nothing
else changes so I think having a whole entire tab would make them think
more actually changed when really their existing code base will do the job
just fine.

**Comment by jgeewax** [comment]
There is a PR! Take a look ! :)

---

Hmm, you think it will confuse folks? I really like the idea of having the base example be super simple, but still showing people that if you're running in EC2 or anywhere else, you just have a couple extra lines...
