### ISSUE TITLE
the acl add doesn't work

### ISSUE THREAD

**Issue by khmereshop** [GoogleCloudPlatform/gcloud-node#569]
the acl does not work. When I display the myFile, It does not object reference to myFile.acl.add

```javascript
var myFile = bucket.file(filename);

console.log(myFile);

myFile.acl.update({
  scope: 'allUsers',
  permission: storage.acl.READER_ROLE
}, function(err, aclObject) {

  console.log('**** error ****');

  console.log(err);
  console.log(aclObject);
});

**Comment by ryanseys** [comment]
Hey @khmereshop sorry for the delay. I'm sorry but I don't really understand the issue here. Can you take a look at [the system tests here](https://github.com/GoogleCloudPlatform/gcloud-node/blob/8c3719ff57f0a03165cc18251e9b57494b94bd0f/system-test/storage.js#L156) where we are testing our `acl.add` method. That might help you make sense of what `acl.add` is meant to do. Your sample code given seems to also be using `acl.update` and not `acl.add` so if you could clarify why and what your code is supposed to show, that'd be great!

**Comment by stephenplusplus** [comment]
@khmereshop are you still having an issue?

**Comment by stephenplusplus** [comment]
Please re-open if you are still experiencing this :)
