### ISSUE TITLE
Why don't we have a section in the docs under storage called Acl ?

### ISSUE THREAD

**Issue by jgeewax** [GoogleCloudPlatform/gcloud-node#573]
Seems that http://googlecloudplatform.github.io/gcloud-node/#/docs/v0.14.0/storage/acl is generated, but we don't have an item in the sidebar. Is that because we inlined the ACL-related methods into the Bucket/File as `whatever.acl.method` ?

**Comment by ryanseys** [comment]
Yep. We don't expose Acl directly to the user, only through Bucket and File, which use this shared Acl class that you're talking about here.

**Comment by jgeewax** [comment]
That makes sense.

So *should* we expose this to the user? Or is it better left as a hidden mix-in style class?

**Comment by stephenplusplus** [comment]
I only like keeping that page hidden because I worry it would be confusing for developers to differentiate between the file / bucket scenarios, then the default Bucket object. Keeping them doc'd on their module pages lets us have more control how the concepts are presented to the user.

But if you guys think it's more helpful having the ACL page as well, I'm cool with it.

**Comment by jgeewax** [comment]
I have no preference at all - I think we're fine as is...
