### ISSUE TITLE
Restrict API call query parameters to what we say we accept

### ISSUE THREAD

**Issue by stephenplusplus** [GoogleCloudPlatform/gcloud-node#653]
Related: #647, #652

Right now, we sometimes kind of blindly pass the user's provided object to the API. We should be sure to only pass through what we say in our docs we accept.

I'm thinking something like:

```js
/**
 * @param query.maxResults
 * @param query.pageSize
 */
Service.prototype.method = function(query, callback) {
  var allowedQueryParameters = ['maxResults', 'pageSize'];
  var requestQuery = util.pluck(query, allowedQueryParameters);
  // If `query` had more on it, we get a new object back with just the
  // params we want the API to receive.

  callApi('POST', '/path', requestQuery);
};
```

**Comment by ryanseys** [comment]
Interesting idea, I've explored a similar idea before in `googleapis` with required parameters [here](https://github.com/google/google-api-nodejs-client/blob/0092d10b6fd4d6740625961e9d08f71e588c98dc/lib/apirequest.js#L109), however sometimes there are an outrageous number of different optional parameters that can be passed which is just tedious to document. Additionally, if implemented, this actually wouldn't really solve the problem of us mis-documenting the required parameters and letting something like #647 sneak through because of our human error. Also, this would make non-breaking additional parameters added to the API silently (which Google likes to do from time to time) effectively refuse that functionality. Yes that'd be good as long as the user files a bug and we fix it, but its still scary to the user when they are doing the right thing and we aren't.

**Comment by stephenplusplus** [comment]
Okay, let's do it the way we're doing it. :+1: 

Will close, anyone feel free to re-open if there's a better solution than "nevermind" :)
