### ISSUE TITLE
Double check that the installation on OS X works as expected...?

### ISSUE THREAD

**Issue by jgeewax** [GoogleCloudPlatform/gcloud-node#660]
I got some feedback that installing on OS X with Node 0.12.x was not as smooth as it should be.

Excluding the typical npm ownership issues (`root` vs `$USER`) it seems that `sse4_crc32` has some problems and our docs don't really say much about it. Can we do a dry run through all of this and see what's needed to make `npm install gcloud` an un-eventful process?

The complaints focused around `sse4_crc32` and `node-gyp`, particularly something about `--no-parallel`  being an invalid flag?

**Comment by stephenplusplus** [comment]
// @anandsuresh

**Comment by anandsuresh** [comment]
@jgeewax @stephenplusplus I just built the latest master branch of the SSE4_CRC32 library on my macbook and it worked fine. Also did an `sudo npm install gcloud` without any errors (had to run it as sudo due to the npm ownership issues).

Any chance of getting some logs of the problematic installation?

With regards to the `--no-parallel` flag, please check out https://github.com/TooTallNate/node-gyp/issues/426 or https://github.com/Unitech/pm2/issues/434.

**Comment by stephenplusplus** [comment]
I use gcloud with OS X every day, and have only run into errors when going between v0.10 of Node and v0.12. Doing that without re-installing the dependencies will cause errors.

If more issues pop up around sse4_crc32, I think we should direct users over to their repo for support. There's not much we can do here, aside from discontinue using it, which I don't think we want to do. @anandsuresh has been great with support, so the few times these issues come in, they'll likely be resolved rather quickly.

Feel free to re-open if this is not a satisfying answer.
