### ISSUE TITLE
Move examples and docs out of the README, point to docs instead

### ISSUE THREAD

**Issue by jgeewax** [GoogleCloudPlatform/gcloud-node#672]
We're seeing people using the README contents on NPM as a source of real documentation, and missing out on the bigger picture because they're not seeing all of the other pieces.

Any objections to removing the README example content (specific snippets for each service) and pointing to the gh-pages docs instead?

**Comment by stephenplusplus** [comment]
I think the readme's job is to quickly make the sell on why gcloud is awesome, and part of that is shoving in the potential user's face how easy it is to "..." as soon as you can. A user going to a readme to look for the link to further documentation is common practice, so I would rather solve how to get the user to see our API documentation links than have the readme completely cater to the user rather than the maybe-user.

Since we already link to the docs at the top of the page and in each service's sub-section, is it possible to get opinions from the users who sourced this feedback to see what we could do better?

**Comment by jgeewax** [comment]
I'll have our UX guy share the results at the end, but it was super clear that the person just wasn't getting to the docs because they thought the README was all there was.

Can we add "for more details on <service>, check out the docs here: <link>" right after the example sections?

Our goal is to funnel people to the gh-pages site ASAP.

**Comment by stephenplusplus** [comment]
Were the participants of the study Node developers? We're super tuned in to the patterns of GitHub + npm + API docs, and how and when to use each resource.

> Can we add "for more details on , check out the docs here: " right after the example sections?

:+1:

**Comment by jgeewax** [comment]
They were, but this one in particular was not SUPER experienced, I'd say a 5/10 Node dev.
