### ISSUE TITLE
Cloud Storage Delete all files with prefix

### ISSUE THREAD

**Issue by javorosas** [GoogleCloudPlatform/gcloud-node#680]
It would be nice if there was a bulk delete for files that satisfy a query in a bucket. Something like:

    myBucket.deleteFiles({ prefix: 'myDirectory/' }, callback);

**Comment by jgeewax** [comment]
Since there's no API call for this, it'd really be a shortcut for...

```javascript
bucket.getFiles({ prefix: 'directory/'}, function(err, files, ...) {
  for (var i in files) {
    files[i].delete();
  }
});
```

which could be super misleading about what's actually happening, **and** might fail half-way through (it wouldn't be an atomic operation). That said, I'll leave this open for discussion...

/cc @stephenplusplus : This (to me) feels like the whole "delete bucket even if it isn't empty" thing where people are going to do it, so we might as well help them do it right (and then if we add an API call to do such a thing, we can swap it for that under the hood without anyone caring).

/cc @Capstan : Any chance we're going to add a long-running operation to delete multiple files in a single request using the same query parameters we provide to [`Objects:list`](https://cloud.google.com/storage/docs/json_api/v1/objects/list)?

**Comment by stephenplusplus** [comment]
I think this is a good idea. Will PR.

**Comment by Capstan** [comment]
@jgeewax Support for additional long-running operations is on our roadmap, yes. As for what the method looks like is still undecided. It may not look like list objects at all. It may cleave more to [lifecycle](https://cloud.google.com/storage/docs/lifecycle) management instead. If you have some specific use cases / design goals in mind, it'd be helpful. (e.g., do you care about people adding objects after the operation starts being deleted or not?)
