### ISSUE TITLE
installation fail with iojs 3.2.0 on Mac OS

### ISSUE THREAD

**Issue by edoardofenati** [GoogleCloudPlatform/gcloud-node#843]

**Comment by stephenplusplus** [comment]
Install directly from master:

```sh
$ npm install --save googlecloudplatform/gcloud-node
```

Our dependency `sse4_crc32` needed to upgrade one of their dependencies to be [compatible with io3](https://github.com/Voxer/sse4_crc32/pull/34). They upgraded and released it under a major bump, so gcloud@0.20.0 doesn't automatically pick it up. However, since our last release, we no longer depend on `sse4_crc32` directly, instead it comes from [hash-stream-validation](http://gitnpm.com/hash-stream-validation), which uses the new sse4_crc32 version.
