### ISSUE TITLE
Can we make gcloud-node auto-detect the projectId if it's in a special environment?

### ISSUE THREAD

**Issue by jgeewax** [GoogleCloudPlatform/gcloud-node#974]
Special environment = Compute Engine or App Engine via Managed VMs?

**Comment by stephenplusplus** [comment]
> App Engine via Managed VMs

I believe so, because it's available as an env var, right? `GAE_LONG_APP_ID`, possibly.

> Compute Engine

I believe you have to hit the metadata server, which complicates this for us, as that is an async operation.

We talked about this in #570 (shortcut: https://github.com/GoogleCloudPlatform/gcloud-node/issues/570#issuecomment-102119291).

What we came up with was... for the same code to go from a dev environment where a project ID will always be required (can't be autodetected) to a production requirement (where it can be autodetected), the user would already have been providing the project ID in dev, only to remove it when pushing to production for the benefit of magic autodetection.

So the resolution was to just require it explicitly, *but* honor a generic env var "`GCLOUD_PROJECT_ID`". I'm not sure what happened to that... I don't think we ever did honor that env var or document it. But then [this issue](https://github.com/GoogleCloudPlatform/gcloud-common-private/issues/17) came along, and afaik, it doesn't look like we decided on one yet?

If we can agree on just a single env var like "GCLOUD_PROJECT_ID", do you still think that's a good way to go for all the reasons we discussed in #570?

**Comment by jgeewax** [comment]
Effectively we're saying to run this to start your app, and this problem goes away, right ? 

```sh
$ export GCLOUD_PROJECT=`curl -L http://metadata.google.internal/computeMetadata/v1beta1/project/project-id`
$ node
```

**Comment by stephenplusplus** [comment]
Yeah that would definitely work (naming of "GCLOUD_PROJECT" tbd).

**Comment by jgeewax** [comment]
Sure -- I think that was the latest proposal in that issue on gcloud-common-private.

**Comment by stephenplusplus** [comment]
Okay cool, I'll get that supported asap!
